//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 01/24/2020 19:32:55
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Bubblz.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    internal sealed partial class Strings
    {
        
        private static ResourceLoader resourceLoader;
        
        /// <summary>
        /// Get or set ResourceLoader implementation
        /// </summary>
        public static ResourceLoader Resource
        {
            get
            {
                if ((resourceLoader == null))
                {
                    Strings.Initialize();
                }
                return resourceLoader;
            }
            set
            {
                resourceLoader = value;
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Platziere mindestens 20 Bubblz um in das nächste Level zu kommen."
        /// </summary>
        public static string Description_Level01
        {
            get
            {
                return Resource.GetString("Description_Level01");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Level 1"
        /// </summary>
        public static string Name_Level01
        {
            get
            {
                return Resource.GetString("Name_Level01");
            }
        }
        
        public static void Initialize()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Strings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Strings");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Strings");
            }
        }
    }
}
